name: poker
version: 0.7.0
description: >-
  A Dart implementation of Texas Hold'em matchup simulator based on Henry Lee's Poker Hand Evaluator.
homepage: https://github.com/axross/poker
repository: https://github.com/axross/poker
environment:
  sdk: ">=2.17.0 <3.0.0"
dependencies:
  bitcount: ^0.3.0
  lints: ^2.0.0
  meta: ^1.8.0
dev_dependencies:
  test: ^1.21.4
