name: poker
version: 0.0.10
description: >-
  A Dart implementation of Texas Hold'em matchup simulator based on Henry Lee's Poker Hand Evaluator.
homepage: https://github.com/axross/poker
repository: https://github.com/axross/poker
environment:
  sdk: ">=2.8.1 <3.0.0"
dependencies:
  meta: ^1.1.8
dev_dependencies:
  benchmark_harness: 1.0.5
  test: 1.15.1
