name: poker
version: 0.3.0
description: >-
  A Dart implementation of Texas Hold'em matchup simulator based on Henry Lee's Poker Hand Evaluator.
homepage: https://github.com/axross/poker
repository: https://github.com/axross/poker
environment:
  sdk: ">=2.12.0 <3.0.0"
dependencies:
  meta: ^1.3.0
dev_dependencies:
  test: ^1.17.12
