name: on Release
on:
  release:
    types:
      - published
jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - run: ls -al
      - name: Publish a new version of Dart package
        uses: k-paxian/dart-package-publisher@1.5
        with:
          credentialJson: ${{ secrets.PUB_CREDENTIAL_JSON }}
          skipTests: true
